[Dispatch File]
File Version       = 1.0
Show ID            = ACR
Show Name          = Acrophobia Netshow

Update Script Server Path   = /acrophobia/content/ChangeoverUpdateScript.ini
BOB Update Script Server Path   = /acrophobia/content/UpdateScript.ini
Content Server Section      = Content Server
Game List Server Section    = Game List Server

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;    Deprecated - old acro support for conversion
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Register CGI Name           = cgi/bezreg0.cgi
Validate CGI Name           = cgi/acrval0.cgi
Query CGI Name              = cgi/bezquery0.cgi
Change CGI Name             = cgi/bezchange0.cgi
Sponsors CGI Name           = cgi-bin/bezsponsors.cgi

Registration Server Section = Registration Server
Web Server Section          = Web Server



;;;; Content Servers ;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Content Server 1]
HTTP Server Name     = 128.11.20.165
HTTP Server Port     = 80


;;[Content Server 2]
;;HTTP Server Name     = 128.11.20.160
;;HTTP Server Port     = 8080

;;;; Game List Servers ;;;;;;;;;;;;;;;;;;;;;;;;;;

[Game List Server 1]
IRC Server Name      = 128.11.20.165
IRC Server Port      = 6666
IRC Server Password  = 
IRC Channel Name     = Acro_List
IRC Channel Password = 
IRC Bot Nickname     = ListNick





;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;    Deprecated - old acro support for conversion
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


;;;; Registration Servers ;;;;;;;;;;;;;;;;;;;;;;

[Registration Server 1]
                       ;dispatch.jack.com
HTTP Server Name     = 192.216.191.27 
HTTP Server Port     = 80
;;;                       ;dev.jack.com
;;;HTTP Server Name     = 192.216.191.143 
;;;HTTP Server Port     = 80
;;;HTTP Server Port     = 8042

;;;; Web Server ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Web Server]
HTTP Server Name     = www.bezerk.com
;HTTP Server Port     = 80  (commented out, no ":80" in URL)
Success Page         = /acro/sponsors.html
;Success Page         = /acrobeta/sponsors.html
Error Page	         = /acro/trouble.html


